import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { headers } from "next/headers";
import { cache } from "react";
import { tenantFetch } from "@/actions/category";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export async function generateMetadata() {
//   const headersList = await headers();
//   const domain = headersList.get("host");
//   console.log(domain);

//   const subdomain = domain?.split(".")[0];
//   console.log(subdomain);

//   return {
//     title: `${subdomain}`,
//     description: "Generated by create next app",
//   };
// }

interface IMetaDataResponse{
  name: string;
  description: string;
  image: string;
  logo: string;
}

export async function generateMetadata() {
  const headersList = await headers();
  const domain = headersList.get("host");
  const subdomain = domain?.split(".")[0];

  if (!subdomain) {
    return null;
  }

  const getTenantMetaData = cache(() => tenantFetch(subdomain, ["name", "description", "logo"]));
  const { data, status, error } = await getTenantMetaData();
  console.log(data,"data");
  console.log(status,"status");
  console.log(error,"error");

  if (!data || status !== 200 || error) {
    return null;
  }

  const { name, description, logo } = data as IMetaDataResponse;

  return{
    title: name,
    description,
    openGraph: {
      title: name,
      description,
      images: [logo],
    },
    twitter: {
      card: "summary_large_image",
      title: name,
      description,
      images: [logo],
      creator: "@vercel",
    },
    icons: [logo],
    metadataBase: new URL(`https://${domain}`),
  }






  




  // const {
  //   name: title,
  //   description,
  //   image,
  //   logo,
  // } = data as {
  //   name: string;
  //   description: string;
  //   image: string;
  //   logo: string;
  // };

  // return {
  //   title,
  //   description,
  //   openGraph: {
  //     title,
  //     description,
  //     images: [image],
  //   },
  //   twitter: {
  //     card: "summary_large_image",
  //     title,
  //     description,
  //     images: [image],
  //     creator: "@vercel",
  //   },
  //   icons: [logo],
  //   metadataBase: new URL(`https://${domain}`),
  //   // Optional: Set canonical URL to custom domain if it exists
  //   // ...(params.domain.endsWith(`.${process.env.NEXT_PUBLIC_ROOT_DOMAIN}`) &&
  //   //   data.customDomain && {
  //   //     alternates: {
  //   //       canonical: `https://${data.customDomain}`,
  //   //     },
  //   //   }),
  // };
}

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>
    </html>
  );
}
