import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { headers } from "next/headers";
import { cache } from "react";
import Footer from "@/components/sections/footer";
import Navbar from "@/components/sections/navbar";
import { Toaster } from "@/components/ui/sonner";

import Image from "next/image";
import Link from "next/link";
import { ReactNode } from "react";
// import CTA from "@/components/cta";
// import ReportAbuse from "@/components/report-abuse";
import { notFound, redirect } from "next/navigation";
import { getStoreBySubdomain } from "@/actions/store";
// import { getSiteData } from "@/lib/fetchers";
// import { fontMapper } from "@/styles/fonts";

interface IMetaDataResponse {
  name: string;
  description: string;
  image: string;
  logo: string;
}

export async function generateMetadata({ params }: { params: { domain: string } }): Promise<Metadata | null> {
  //   const headersList = await headers();
  //   const domain = headersList.get("host");
  //   const subdomain = domain?.split(".")[0];

  //   if (!subdomain) {
  //     return null;
  //   }

  const domain = decodeURIComponent(params.domain);
  // const domain = decodeURIComponent("https://sss.fenzora.com/");
  // const domain = "https://sss.fenzora.com/";
  // const data = await getSiteData(domain);

  const headersList = await headers();
  // const domain = headersList.get("host");
  // const subdomain = domain?.split(".")[0];
 
  const subdomain = domain.replace(/^https?:\/\//, "").split(".")[0];
  console.log("subdomainhaita", subdomain);


  const response = await getStoreBySubdomain(subdomain);

  if (!response) {
    return null;
  }

  // const {
  //   name: title,
  //   description,
  //   image,
  //   logo,
  // } = data as {
  //   name: string;
  //   description: string;
  //   image: string;
  //   logo: string;
  // };

  const logo = response.data?.store_logo;

  return {
    title: response.data?.store_name,
    description: "This is a description",
    openGraph: {
      title: response.data?.store_name,
      description: "This is a description",
      // images: [image],
    },
    twitter: {
      card: "summary_large_image",
      title: response.data?.store_name,
      description: "This is a description",
      // images: [image],
      creator: "@vercel",
    },
    // icons: [logo],
    icons: [logo ? new URL(logo) : new URL("https://www.google.com/favicon.ico")],
    metadataBase: new URL(`https://${domain}`),
    // Optional: Set canonical URL to custom domain if it exists
    // ...(params.domain.endsWith(`.${process.env.NEXT_PUBLIC_ROOT_DOMAIN}`) &&
    //   data.customDomain && {
    //     alternates: {
    //       canonical: `https://${data.customDomain}`,
    //     },
    //   }),
  };
}

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({ params, children }: Readonly<{ params: { domain: string }; children: React.ReactNode }>) {
  // const domain = decodeURIComponent(params.domain);
  // const data = await getSiteData(domain);

  // if (!data) {
  //   notFound();
  // }

  // // Optional: Redirect to custom domain if it exists
  // if (domain.endsWith(`.${process.env.NEXT_PUBLIC_ROOT_DOMAIN}`) && data.customDomain && process.env.REDIRECT_TO_CUSTOM_DOMAIN_IF_EXISTS === "true") {
  //   return redirect(`https://${data.customDomain}`);
  // }

  return (
    <html lang="en">
      <body>
        <div>
          <div className=" fixed w-full z-50">
            <Navbar />
          </div>
          <div className=" pt-16">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
